## ---- include = FALSE---------------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

## ---- eval = FALSE------------------------------------------------------------
#  # clone the repo and `Install and Restart`
#  # or `devtools::load_all()`
#  
#  #remotes::install_bitbucket(repo = "monkeytronics/r-analytics", subdir = "monkeyr")
#  devtools::install_github("monkeytronics/monkeyr", build_vignettes = TRUE)

## ---- eval = FALSE------------------------------------------------------------
#  library(monkeyr)
#  
#  wrangled_devices <- wrangle_devices(params$filtered_devices)
#  
#  wrangled_weather <- wrangle_weather(params$filtered_weather)
#  
#  wrangled_obs    <- wrangle_observations(
#    filtered_obs   = params$filtered_obs,
#    devices        = wrangled_devices,
#    weather        = wrangled_weather
#  )
#  
#  data_volume     <- get_data_volume(
#    observations   = wrangled_obs,
#    from_timestamp = params$fromTimeStamp,
#    to_timestamp   = params$toTimeStamp
#  )
#  
#  devices_for_map <- get_devices_for_map(
#    devices        = wrangled_devices,
#    data_volume    = data_volume
#  )
#  
#  wrangled_devices<- remove_excluded_devices(
#    target_data    = wrangled_devices,
#    data_volume    = data_volume
#  )
#  
#  wrangled_obs    <- remove_excluded_devices(
#    target_data    = wrangled_obs,
#    data_volume    = data_volume
#  )

## ---- eval = FALSE------------------------------------------------------------
#  set_options(observations = wrangled_obs)

## ---- eval = FALSE------------------------------------------------------------
#  ts_chart(
#    observations = wrangled_obs,
#    from_timestamp = test_params()$fromTimeStamp,
#    to_timestamp = test_params()$toTimeStamp,
#    target_variable = "hum"
#  )

## ---- eval = FALSE------------------------------------------------------------
#  ts_chart(
#    observations = wrangled_obs,
#    from_timestamp = test_params()$fromTimeStamp,
#    to_timestamp = test_params()$toTimeStamp,
#    target_variable = "temp"
#  )

## ---- eval = FALSE------------------------------------------------------------
#  run_test_report(
#      report       = "home",           ## rmd file!
#      dummy_data   = "monkey_a",       ## dummy data from inst/dummy-data
#      dummy_params = "params_blank.txt"    ## dummy params from inst/dummy-params
#  )

## ---- eval = FALSE------------------------------------------------------------
#  # the system.file calls are to access the example data installed with the package
#  # in production, the list of parameters will be generated by the script calling this
#  # report
#  
#    obs           <- "/tmp/obs.csv"
#    dev           <- "/tmp/dev.csv"
#    weather       <- "/tmp/weather.csv"
#    interv        <- "/tmp/interv.csv"
#    from          <- 1627639151
#    to            <- 1630317551
#  
#    par_list <- monkeyr::make_params_list(
#      filtered_obs           = obs,
#      filtered_devices       = dev,
#      filtered_weather       = weather,
#      filtered_interventions = interv,
#      fromTimeStamp          = from_ts,
#      toTimeStamp            = to_ts
#    )
#  
#    temporary_directory      <- Sys.getenv("TMPDIR", "/tmp")
#    outfile                  <- file.path(temporary_directory, paste0("flexi", ".html"))
#  
#  # knit with default file name and output dir
#    monkeyr::knit_report(
#      param_list = par_list,
#      output_file = outfile,
#      output_dir = temporary_directory,
#      intermediates_dir = temporary_directory,
#      envir = new.env()
#    )

