```{r echo=FALSE, include=FALSE}

message(paste0("\nMAP REGIONAL : Entering child rmd"))

tryCatch(
  {
      
    library(rgdal); message(paste0("\nMAP REGIONAL : rgdal"))
    library(dplyr); message(paste0("\nMAP REGIONAL : dplyr"))
    # library(viridis)
    library(stringi); message(paste0("\nMAP REGIONAL : stringi "))
    library(sf); message(paste0("\nMAP REGIONAL : sf "))
    library(cowplot); message(paste0("\nMAP REGIONAL : cowplot "))
    library(ggrepel); message(paste0("\nMAP REGIONAL : ggrepel "))
    library(ggspatial); message(paste0("\nMAP REGIONAL : ggspatial "))
    
    library(maps); message(paste0("\nMAP REGIONAL : maps "))
    library(mapdata); message(paste0("\nMAP REGIONAL : mapdata "))
    library(RColorBrewer); message(paste0("\nMAP REGIONAL : RColorBrewer "))
    library(countrycode); message(paste0("\nMAP REGIONAL : countrycode "))
    data(world.cities); message(paste0("\nMAP REGIONAL : data(world.cities) "))
      
    sf::sf_use_s2(FALSE)
    message(paste0("\nMAP REGIONAL : After library loading"))
    
      
      ##testing with UK datasets 
      # uk_county <- geojson_read('Counties_Unitary.json',what='sp')
      # uk_county <- sf::st_as_sf(uk_county)
      # uk_county <- sf::st_make_valid(uk_county) ####import for EU based spatial files
      # uk_county <- cbind(uk_county, st_coordinates(st_centroid(uk_county)))
      # uk_county <- sf::st_transform(uk_county,crs = 4326)
      #
      # uk_region <- geojson_read('Local_Authority_District.geojson',what='sp')
      # uk_region <- sf::st_as_sf(uk_region)
      # uk_region <- sf::st_make_valid(uk_region)
      # uk_region <- cbind(uk_region, st_coordinates(st_centroid(uk_region)))
      # uk_region <- sf::st_transform(uk_region,crs = 4326)
      
      # country <- uk_region
      # region = 'Manchester'
      # regions_map <- uk_county
      # country_points <- nz_points
      # plottitle <- 'Testing UK mapping '
      # fill_col_district <- 'st_areashape'
      # district_label <- 'ctyua17nm'
      # filter_col_region <- 'ctyua17nm'
      
    
    ###### New Zealand ########  
      #### READ SHAPEFILES/SPATIAL DATA
      nz <- sf::st_read("../maps/nz/nz_ta.geojson")
      nz_regions <- sf::st_read("../maps/nz/nz_region.geojson")
      
      #### Convert to SF objects and generate centroids
      nz <- sf::st_as_sf(nz)
      nz <- cbind(nz, sf::st_coordinates(sf::st_centroid(nz)))
      nz_regions <- sf::st_as_sf(nz_regions)
      nz_regions <- cbind(nz_regions, sf::st_coordinates(sf::st_centroid(nz_regions)))
    
      
    ###### Australia ########  
      #### READ SHAPEFILES/SPATIAL DATA  
      aus <- sf::st_read("../maps/au/aus_lga.geojson")
      aus_regions <- sf::st_read("../maps/au/aus_state.geojson")
      
      #### Convert to SF objects and generate centroids
      aus <- sf::st_as_sf(aus)
      aus <- cbind(aus, sf::st_coordinates(sf::st_centroid(aus)))
      aus_regions <- sf::st_as_sf(aus_regions)
      aus_regions <- sf::st_make_valid(aus_regions)
      # aus_regions<- cbind(aus_regions, sf::st_coordinates(sf::st_centroid(aus_regions)))
    
      
    ###### Grab CountryName from Devices (New Zealand -> NZ; Australia -> AU, Ireland -> IE; etc. )
      countryName <- names(which.max(table(wrangled_devices$country)))
      print(countryName)  
    
      countryCode <- countrycode::countrycode(countryName, origin = 'country.name', destination = 'iso2c')
      # countryCode <- countrycode("New Zealand", origin = 'country.name', destination = 'iso2c')
      
    ###### Map location data table #######
      map_location <- devices_for_map %>%
       # dplyr::filter(connected  == 1) %>%
        dplyr::filter(has_coords == 1)
      
      
    ###### Check for Matching Region / District #######
      map_location_row <- map_location %>%
        rowwise() %>%
        
      # Match Region
        mutate(TA2016_NAM = nz$TA2016_NAM [
          which.min(
            sqrt((long - nz$X)^2 + (lat - nz$Y)^2)
          )]
        ) %>%
      # Match Local District
        mutate(REGC2016_N = nz_regions$REGC2016_N[
          which.min(
            sqrt((long - nz_regions$X)^2 + (lat - nz_regions$Y)^2)
          )]
        )
      
      # function to get modal value of character vector
      getmode <- function(v) {
        uniqv <- unique(v)
        uniqv[which.max(tabulate(match(v, uniqv)))]
      }
      
      modeDistrict <-  getmode(map_location_row$TA2016_NAM) 
      modeRegion   <-  getmode(map_location_row$REGC2016_N) 
      
      # Count % of districts values matching
      districtConc <- map_location_row %>%
        filter(TA2016_NAM == modeDistrict) %>%
        nrow() * 100 / nrow(map_location_row)
      
      # Count % of region values matching (not used)
      regionConc <- map_location_row %>%
        filter(TA2016_NAM == modeDistrict) %>%
        nrow() * 100 / nrow(map_location_row)
      
      if (districtConc > 80) {
        print("Let's limit the inset to a single district! ")
      }
      
      
      
    ###### Get Cities data
      major_cities <- world.cities%>%
      filter(country.etc == countryName) %>%
      filter(pop > 10000)  
      
      
      
    ###### Function takes country spatial files ,  internal boundaries and connected data and produces output map.
      drawRegionalMap <- 
        function(country, 
                 cities, 
                 regions_map, 
                 region, 
                 country_points, 
                 plottitle, 
                 filter_col_region, 
                 fill_col_district, 
                 district_label, 
                 insert_x = 0.1,          # default val
                 insert_y = 0.4,          # default val 
                 insert_height = 0.5,     # default val
                 insert_width = 0.5,...)  # default val
      {
        
          
      ### Ryan: it sets the gradient limits on the fill color
          min <- min(country[[fill_col_district]])
          max <- max(country[[fill_col_district]])
          # print(min)
          # print(max)
          
        
      ### FUNC
          bbox_new <- st_bbox(country) # current bounding box
      
          xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
          yrange <- bbox_new$ymax - bbox_new$ymin # range of y values
      
          bbox_new[1] <- bbox_new[1] - (0.2 * xrange) # xmin - left
          bbox_new[3] <- bbox_new[3] + (0.2 * xrange) # xmax - right
          #bbox_new[2] <- bbox_new[2] - (0.5 * yrange) # ymin - bottom
          #bbox_new[4] <- bbox_new[4] + (0.5 * yrange) # ymax - top
          bbox_new <- bbox_new%>%  # take the bounding box ...
          st_as_sfc()
      
      
      ### INSET MAP bounding box
          tas <- regions_map %>%
          filter(.data[[filter_col_region]] == region)
      
          default_font_color <- "#4e4d47"
          default_background_color <- "#ffffff"
          default_font_family <- "sans"
          default_caption <- paste0("Source: ")
      
      
      ###custom theme
          theme_map <- function(...) {
            theme_minimal() +
            theme(
              text = element_text(family = default_font_family,
                                  color = default_font_color,size = 9),
              # remove all axes
              axis.line = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.ticks = element_blank(),
              # add a subtle grid
              # panel.grid.major = element_line(color = "#dbdbd9", size = 0.2),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              # background colors
              plot.background = element_rect(fill = default_background_color,
                                             color = NA),
              panel.background = element_rect(fill = default_background_color,
                                             color = NA),
              legend.background = element_rect(fill = default_background_color,
                                               color = NA),
              # borders and margins
              plot.margin = unit(c(.5, .5, .2, .5), "cm"),
              panel.border = element_blank(),
              panel.spacing = unit(c(-.1, 0.2, .2, 0.2), "cm"),
              # titles
              legend.title = element_text(size = 11),
              legend.text = element_text(size = 8, hjust = 0,
                                         color = default_font_color),
              plot.title = element_text(size = 11, hjust = 0.5,
                                        color = default_font_color),
              plot.subtitle = element_text(size = 10, hjust = 0.5,
                                           color = default_font_color,
                                           margin = margin(b = -0.1,
                                                           t = -0.1,
                                                           l = 2,
                                                           unit = "cm"),
                                           debug = F),
              # captions
              plot.caption = element_text(size = 7,
                                          hjust = .5,
                                          margin = margin(t = 0.2,
                                                          b = 0,
                                                          unit = "cm"),
                                          color = "#939184"),
              ...
            )
          }
      
      ### MAIN MAP
          main_map <- country %>%
            ggplot() +
            geom_sf(aes(fill=.data[[fill_col_district]]),
                      lwd = 0,
                      colour = "white") +
            geom_sf(data = bbox_new, fill = NA, color = "black", size = 0.3) +
            geom_sf(
                    data = country,
                    fill = "transparent",
                    color = "white",
                    size = 0.2
                  ) +
            #geom_text_repel(aes(X, Y, label = .data[[district_label]]), max.overlaps=10,size = 1.8,force=2,force_pull=2) +
            ggspatial::annotation_scale(location = "br", width_hint = 0.2) + ## GGSPATIAL FUNCTION
            theme_void()+
            coord_sf(expand = FALSE) +
            
            # #ggtitle("Observation Sites", subtitle = "(2 sites in Palm Beach County, Florida)")+
            # scale_fill_viridis(
            #   # alpha = 0.5,
            #   option = "magma",
            #   direction = -1,
            
            scale_fill_gradientn(
              limits = c(min, max),
              colours=brewer.pal(7,"Blues"),
              
              name = "Area Square KM",
              # here we use guide_colourbar because it is still a continuous scale
              guide = guide_colorbar(
                direction = "horizontal",
                barheight = unit(2, units = "mm"),
                barwidth = unit(50, units = "mm"),
                draw.ulim = F,
                title.position = 'top',
                # some shifting around
                title.hjust = 0.7,
                label.hjust = 0.7
            )) +
            geom_point(data = country_points, aes(x = long, y = lat,colour = connected),size=0.4)+
            scale_color_manual(values = c("TRUE" = "#069C36", "FALSE" = "#C03653")) +
            
            ### cities
            geom_point(data = cities, aes(x = long, y = lat),size=0.5) +
            #geom_text_repel(aes(X, Y, label = .data[[district_label]]), size = 1.3,max.overlaps =20) +
            geom_text_repel(
              data = major_cities, 
              aes(x=.data[['long']], y=.data[['lat']], label = .data[['name']]), 
              max.overlaps=20, 
              size = 2.0, 
              force=2, 
              force_pull=2) +
            
            labs(title = plottitle,
                   x = "", y = "") +
              geom_rect(
                xmin = st_bbox(tas)[1],
                ymin = st_bbox(tas)[2],
                xmax = st_bbox(tas)[3],
                ymax = st_bbox(tas)[4],
                fill = NA,
                colour = "black",
                size = 0.6
              ) +
            theme_map() +
            theme(legend.position = "none")+
            guides(colour = "none")
      
      
      ### INSERT MAP
          inset_bbox <- st_bbox(tas)%>% st_as_sfc()
          country_cropped <- st_crop(country, inset_bbox)
          inset <- country_cropped %>%
            ggplot() +
            geom_sf(aes(fill=.data[[fill_col_district]]),
                      lwd = 0,
                      colour = "white") +
            # scale_fill_viridis(
            #   # alpha = 0.5,
            #   option = "magma",
            #   direction = -1,
            
            
            geom_sf(data = country_cropped,fill = "transparent",color = "white",size = 0.2) +
            scale_fill_gradientn(
              limits = c(min,max),
              colours= brewer.pal(7,"Blues"),
            
            
              name = "Area Square KM",
              # here we use guide_colourbar because it is still a continuous scale
              guide = guide_colorbar(
                direction = "horizontal",
                barheight = unit(2, units = "mm"),
                barwidth = unit(50, units = "mm"),
                draw.ulim = F,
                title.position = 'top',
                # some shifting around
                title.hjust = 0.7,
                label.hjust = 0.7
            )) +
            geom_sf(data = inset_bbox, fill = NA, color = "black", size = 0.4) +
            # #geom_text_repel(aes(X, Y, label = .data[[district_label]]), size = 1.3,max.overlaps =3) +
            # geom_point(data = country_points, aes(x = long, y = lat,colour = factor(connected)),size=1.2)+
            # # scale_color_manual(values = c("TRUE" = "#065C36", "FALSE" = "#D006D3")) +
            # scale_color_manual(values = c("TRUE" = "#008450", "FALSE" = "#B81D13")) +
            
            
            ### label names in inset
            geom_text_repel(aes(X, Y, label = .data[[district_label]]), size = 2.0, max.overlaps = 10) +
            geom_point(data = country_points, aes(x = long, y = lat,colour = factor(connected)),size=1.0)+
            scale_color_manual(values = c("TRUE" = "#069C36", "FALSE" = "#C03653")) +
            
            
            theme_void()+
            coord_sf(
                      xlim=st_bbox(tas)[c(1,3)],
                      ylim = st_bbox(tas)[c(2,4)],
                      expand = FALSE) +
              theme(legend.position = "bottom") +
              theme(text = element_text(size = 9,family = 'sans')) +
              ggtitle(region) +
              guides(fill = "none",col=guide_legend("Connection Status",
                                                    title.position = 'top',
                # some shifting around
                title.hjust = 0.7,
                label.hjust = 0.7))
      
      ### Combine Maps
          gg_inset_map1 <- ggdraw() +
          draw_plot(main_map) +
          #draw_plot(inset, x = insert_x, y = insert_y, width = insert_width, height = insert_height)
          #draw_plot(inset, x = 0.05, y = 0.5, width = 0.5, height = 0.5)
          draw_plot(inset, x = insert_x, y = insert_y, width = insert_width, height = insert_height)
    
          return (gg_inset_map1)
      }
      
      
    
    # Draw Regional Map
      myMap <- drawRegionalMap(
        country           =  nz,
        cities            =  major_cities,
        regions_map       =  nz_regions,
        region            =  modeRegion,
        country_points    =  map_location,
        plottitle         = 'Connection Status across New Zealand Regions',
        filter_col_region = 'REGC2016_N', # TA2016_NAM
        fill_col_district = 'AREA_SQ_KM',
        district_label    = 'TA2016_NAM',
        insert_x          = 0.10,       # distance from Left
        insert_y          = 0.40,       # distance from bottom
        insert_height     = 0.43,       # height of plot
        insert_width      = 0.38        # width  of plot
      )
      
    # # Draw District Map
    #   myMap <- drawDistrictMap(
    #     country           =  nz,
    #     regions_map       =  nz_regions,
    #     region            =  modeRegion,
    #     country_points    =  map_location,
    #     plottitle         = 'Connection Status across New Zealand Regions',
    #     filter_col_region = 'REGC2016_N',
    #     fill_col_district = 'AREA_SQ_KM',
    #     district_label    = 'TA2016_NAM'
    #   )
  
  
  },
    error = function(cond) {
      monkeyr::monkey_knit_error(err = cond, resource = "mapping")
  }
)
  
```


### 1.2 Deployment & Coverage Map for `r modeDistrict`

```{r echo=FALSE} 
  count_all       <- nrow(devices_for_map)
  count_connected <- nrow(devices_for_map %>% filter(connected == TRUE))
  count_no_coords <- nrow(devices_for_map %>% filter(has_coords == FALSE))
```

Of `r count_all` deployed devices, `r count_connected` (shown in green) connected well, with approximate locations. Those in red connected very poorly or not at all.  `r count_no_coords` devices could not be shown on the map due to missing location data.

```{r echo=FALSE, fig.dim=c(8,8)}
  myMap
```

##### Figure 1.2: Device Map
